name: OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build OS
      run: cargo build --verbose
      working-directory: ./os
    - name: Run OS tests
      run: cargo test --verbose
      working-directory: ./os
    - name: Build user app
      run: cargo build --verbose
      working-directory: ./user
    - name: Run user app tests
      run: cargo test --verbose
      working-directory: ./user
